### ISSUE TITLE
Package not working with TeX Live 2024

### ISSUE THREAD

**Issue by khanson679** [adamb924/ot-tableau#3]
I am unable to create any tableaux in the current version of TeX Live. The problem seems to be with the `arydashln` package. loaded by `ot-tableau`. Upon testing, it seems that the package has become incompatible `array` as well as `colortbl`, the latter also loaded by `ot-tableau`.

The workaround I wound was to disable dashed lines using command `\ADLinactivate` provided by `arydashln`. MWE provided below.

```
\documentclass{article}
\usepackage{ot-tableau}
% \ADLinactivate % uncomment to compile

\begin{document}
\begin{tableau}{c|c|c:c}
\inp{abcde} \const{A} \const{B} \const{C} \const{D}
\cand[\Optimal]{abcde} \vio{}   \vio{}   \vio{} \vio{}
\cand{abzzz}          \vio{*!} \vio{}   \vio{} \vio{*}
\cand{abyyy}           \vio{}   \vio{*!} \vio{} \vio{}
\cand{nom-mu}          \vio{}   \vio{*!} \vio{} \vio{*}
\end{tableau}
\end{document}
```

I will report this to the author of `arraydashln`, but in the meantime you may want to add an option to disable shading in `ot-tableau` so that we can at least have dashed lines. I tried to modify the source code myself but was unsuccessful as many changes need to be made.

**Comment by adamb924** [comment]
I don't have the code in front of me, but finding packages that create shaded cells and dashed lines has been most of the work on this package. 

Is your comment referring to the current CTAN version? There are two branches of the repository, one of which might work.

**Comment by khanson679** [comment]
The version from TeX Live 2024  is 2023-08-01, which is also the newest CTAN version. The "shading" branch from Github does work, since it doesn't load `arydashln` at all.

**Comment by amunn** [comment]
I think this issue has been fixed. The sample code compiles fine for me with a current TL.

**Comment by adamb924** [comment]
The `arydashln` maintainers must have fixed it. Thanks for mentioning that!

**Comment by khanson679** [comment]
Bizarrely, it was still unfixed for me. I ended up reinstalling TeX Live,
and now the test document compiles. My existing install was an upgrade from
v2023 to v2024, so perhaps that was the root of the problem. Mentioning
this here just in case anyone else runs into this problem.
